//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datatalbe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        [Display(Name="Employee Id")]
        public int Id { get; set; }
        [Display(Name = "Employee Name")]
        public string eName { get; set; }
        [Display(Name = "Employee Cell")]
        public string eCell { get; set; }
        [Display(Name = "Employee Phone")]
        public string ePhone { get; set; }
        [Display(Name = "Employee Email")]
        public string eEmail { get; set; }
        [Display(Name = "Depertment Name")]
        public Nullable<int> dId { get; set; }
    }
}
